# Generated by Django 3.1.5 on 2021-01-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210127_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book_author',
            field=models.CharField(max_length=80),
        ),
    ]
