# Generated by Django 3.1.5 on 2021-01-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210127_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.BooleanField(default=False),
        ),
    ]
