# Generated by Django 3.1.5 on 2021-01-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book_title',
            field=models.CharField(max_length=80),
        ),
    ]
